In [2]:
import numpy as np

1

In [3]:
#bukan tensor?
Tensor = np.array([[23, 50, 7, 12], [57, 67, 99, 43], [75, 21, 57, 12], [87, 26, 18, 84]])
Tensor

array([[23, 50,  7, 12],
       [57, 67, 99, 43],
       [75, 21, 57, 12],
       [87, 26, 18, 84]])

2

In [7]:
A = np.array([[23, 50, 19], [7, 12, 109], [57, 67, 98]])
B = np.array([17, 22, 19])

In [8]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [9]:
B

array([17, 22, 19])

In [10]:
A*B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

3

Transpose

In [12]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [13]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

In [14]:
np.linalg.det(A)

131344.0000000002